model_name_or_path: mistralai/Mistral-7B-Instruct-v0.2
model_revision: main
torch_dtype: bfloat16
<<<<<<< HEAD:recipes/zephyr-7b-beta/sft/config_full.yaml
attn_implementation: flash_attention_2
=======
use_flash_attention_2: false
>>>>>>> 276ade04b2ffef82ec58d16e711a6d9c51bd265e:recipes/zephyr-7b-beta/sft/mistral.yaml

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
dataset_mixer:
  chtmp223/suri: 1.0
dataset_splits:
- train
preprocessing_num_workers: 48

# SFT trainer config
bf16: true
<<<<<<< HEAD:recipes/zephyr-7b-beta/sft/config_full.yaml
do_eval: true
eval_strategy: epoch
=======
>>>>>>> 276ade04b2ffef82ec58d16e711a6d9c51bd265e:recipes/zephyr-7b-beta/sft/mistral.yaml
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: suri-sft-v0.2-mixed
hub_strategy: all_checkpoints
hub_always_push: true
hub_private_repo: true
learning_rate: 5.0e-07
log_level: info
logging_steps: 10 
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 15024
max_steps: -1
num_train_epochs: 3
output_dir: /scratch/workspace/ctpham_umass_edu-ft/sft-v0.2-mixed
overwrite_output_dir: true
per_device_train_batch_size: 2
push_to_hub: true
hub_private_repo: true
remove_unused_columns: true
report_to:
- wandb
save_strategy: "epoch"
save_steps: 3
save_total_limit: 3
seed: 42
warmup_ratio: 0.1
run_name: sft-v0.2-mixed